[package]
name = "seen_ir"
version = "0.1.0"
edition = "2021"
description = "IR generation and optimization for the Seen programming language"

[dependencies]
# LLVM bindings
inkwell = { version = "0.6.0", features = ["llvm18-1"] } 

# Seen language components
seen_parser = { path = "../seen_parser" }

# Error handling
thiserror = "2.0.12"

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }

# Logging
log = "0.4"
