[package]
name = "seen_ir"
version = "0.1.0"
edition = "2021"
description = "IR generation and optimization for the Seen programming language"

[dependencies]
# LLVM bindings
inkwell = { version = "0.6.0", features = ["llvm18-1"] } 

# Seen language components
seen_parser = { path = "../seen_parser" }
seen_lexer = { path = "../seen_lexer" }

# Error handling
thiserror = { workspace = true }

# Serialization/Deserialization
serde = { workspace = true }

# Logging
log = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
pretty_assertions = { workspace = true }
test-case = { workspace = true }
rstest = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }
