name = "English"
description = "English Type Definition Keywords"

[keywords]
"data" = "KeywordStruct"
"enum" = "KeywordEnum"
"spec" = "KeywordSpec"
"impl" = "KeywordImpl"
"type" = "KeywordType"
"class" = "KeywordClass"
"sealed" = "KeywordSealed"
"object" = "KeywordObject"
"interface" = "KeywordInterface"
"open" = "KeywordOpen"
"final" = "KeywordFinal"
"abstract" = "KeywordAbstract"
"override" = "KeywordOverride"
"lateinit" = "KeywordLateinit"
"companion" = "KeywordCompanion"
"extension" = "KeywordExtension"
