#!/usr/bin/env python3
"""Generate the pinned Unicode category tables used by seen_tokenizers."""

from __future__ import annotations

import argparse
import hashlib
import unicodedata
from pathlib import Path


PINNED_UNICODE_VERSION = "16.0.0"


def ranges_for(predicate) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start = -1
    previous = -1
    for codepoint in range(0x110000):
        if predicate(codepoint):
            if start < 0:
                start = codepoint
            previous = codepoint
        elif start >= 0:
            ranges.append((start, previous))
            start = -1
    if start >= 0:
        ranges.append((start, previous))
    return ranges


def render_ranges(name: str, ranges: list[tuple[int, int]]) -> str:
    values = ", ".join(f"{start}, {end}" for start, end in ranges)
    return f"let {name}: Array<Int> = [{values}]\n"


def render() -> str:
    if unicodedata.unidata_version != PINNED_UNICODE_VERSION:
        raise SystemExit(
            "Unicode database mismatch: expected "
            f"{PINNED_UNICODE_VERSION}, got {unicodedata.unidata_version}"
        )

    letters = ranges_for(lambda cp: unicodedata.category(chr(cp)).startswith("L"))
    numbers = ranges_for(lambda cp: unicodedata.category(chr(cp)).startswith("N"))
    whitespace = ranges_for(lambda cp: chr(cp).isspace())
    evidence = bytearray()
    for codepoint in range(0x110000):
        evidence.extend(unicodedata.category(chr(codepoint)).encode("ascii"))
        evidence.append(1 if chr(codepoint).isspace() else 0)
    digest = hashlib.sha256(evidence).hexdigest()

    return """/// Generated by scripts/generate_unicode_tables.py. Do not edit.
/// The compact inclusive ranges are deterministic for Python UCD 16.0.0.

let SEEN_TOKENIZERS_UNICODE_VERSION: String = \"16.0.0\"
let SEEN_TOKENIZERS_UNICODE_DATA_SHA256: String = \"%s\"

%s%s%s
fun unicodeRangeContains(ranges: Array<Int>, codepoint: Int) r: Bool {
    if codepoint < 0 or codepoint > 0x10FFFF { return false }
    var low = 0
    var high = ranges.length() / 2
    while low < high {
        let middle = low + (high - low) / 2
        let start = ranges[middle * 2]
        let end = ranges[middle * 2 + 1]
        if codepoint < start { high = middle }
        else if codepoint > end { low = middle + 1 }
        else { return true }
    }
    return false
}

fun unicodeIsLetter(codepoint: Int) r: Bool {
    return unicodeRangeContains(UNICODE_LETTER_RANGES, codepoint)
}

fun unicodeIsNumber(codepoint: Int) r: Bool {
    return unicodeRangeContains(UNICODE_NUMBER_RANGES, codepoint)
}

fun unicodeIsWhitespace(codepoint: Int) r: Bool {
    return unicodeRangeContains(UNICODE_WHITESPACE_RANGES, codepoint)
}
""" % (
        digest,
        render_ranges("UNICODE_LETTER_RANGES", letters),
        render_ranges("UNICODE_NUMBER_RANGES", numbers),
        render_ranges("UNICODE_WHITESPACE_RANGES", whitespace),
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            raise SystemExit("generated Unicode tables are stale")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
