name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test

      - name: Package extension
        run: npm run package

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
          name: "Release v${{ steps.get_version.outputs.VERSION }}"
          body: |
            ## Changes in v${{ steps.get_version.outputs.VERSION }}
            
            ### Features
            - Enhanced language support
            - Improved performance
            - Bug fixes and stability improvements
            
            ### Installation
            1. Download the `.vsix` file below
            2. Open VSCode
            3. Run `Extensions: Install from VSIX...`
            4. Select the downloaded file
            
            Or install from the marketplace: [Seen Language](https://marketplace.visualstudio.com/items?itemName=seen-lang.seen)
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to VSCode Marketplace
        if: success()
        run: npx vsce publish --pat ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Publish to Open VSX Registry
        if: success()
        run: npx ovsx publish --pat ${{ secrets.OVSX_TOKEN }}
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}