[package]
name = "seen_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
seen_lexer = { path = "../seen_lexer" } # Parser needs tokens from lexer
seen_ir = { path = "../seen_ir" }       # Parser might directly build an AST defined in seen_ir
# For error handling
thiserror = "2.0.12"
chumsky = "0.10.1"
