[tool.tarpaulin]
exclude-files = [
    "*/tests/*",
    "*/benches/*", 
    "*/examples/*",
    "target/*"
]
ignore-panics = true
ignore-tests = true
out = ["Html", "Xml", "Lcov"]
output-dir = "target/coverage"
run-types = ["Tests", "Doctests"]
timeout = 120