[package]
name = "seen_advanced"
version = "0.1.0"
edition = "2021"
description = "Advanced features (effects, contracts, metaprogramming) for Seen"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
pretty_assertions = { workspace = true }