name = "Spanish"
description = "Spanish Type Definition Keywords"

[keywords]
"estructura" = "KeywordStruct"
"enumeración" = "KeywordEnum"
"rasgo" = "KeywordSpec"
"implementar" = "KeywordImpl"
"tipo" = "KeywordType"
"clase" = "KeywordClass"
"sellado" = "KeywordSealed"
"objeto" = "KeywordObject"
"interfaz" = "KeywordInterface"
"abierto" = "KeywordOpen"
"final" = "KeywordFinal"
"abstracto" = "KeywordAbstract"
"anular" = "KeywordOverride"
"init_tardío" = "KeywordLateinit"
"compañero" = "KeywordCompanion"
"extensión" = "KeywordExtension"
"rasgo_tipo" = "KeywordTrait"
"datos" = "KeywordData"
"extiende" = "KeywordExtends"
"distinto" = "KeywordDistinct"
"unión" = "KeywordUnion"
