name = "Spanish"
description = "Spanish Memory Management Keywords"

[keywords]
"mover" = "KeywordMove"
"prestar" = "KeywordBorrow"
"en_lugar" = "KeywordInout"
"región" = "KeywordRegion"
"arena" = "KeywordArena"
