name = "Spanish"
description = "Spanish Control Flow Keywords"

[keywords]
"función" = "KeywordFun"
"si" = "KeywordIf"
"sino" = "KeywordElse"
"mientras" = "KeywordWhile"
"para" = "KeywordFor"
"en" = "KeywordIn"
"coincidir" = "KeywordMatch"
"romper" = "KeywordBreak"
"continuar" = "KeywordContinue"
"retornar" = "KeywordReturn"
"cuando" = "KeywordWhen"
"intentar" = "KeywordTry"
"capturar" = "KeywordCatch"
"finalmente" = "KeywordFinally"
"lanzar_error" = "KeywordThrow"
"bucle" = "KeywordLoop"
"diferir" = "KeywordDefer"
"afirmar" = "KeywordAssert"
