[project]
name = "hello_world"
version = "0.1.0"
author = "Seen Language Team"
language = "en"  # Default to English, can be "ar" for Arabic

[build]
targets = ["native"]
optimize = "speed"

[dependencies]
# No external dependencies for this simple example

[format]
line_width = 60
indent = 2
trailing_comma = false
document_types = [".seen", ".md", ".toml"]