name = "Russian"
description = "Russian Modifier Keywords"

[keywords]
"встроенный" = "KeywordInline"
"овеществленный" = "KeywordReified"
"перекрестно_встроенный" = "KeywordCrossinline"
"не_встроенный" = "KeywordNoinline"
"оператор" = "KeywordOperator"
"инфиксный" = "KeywordInfix"
"хвостовая_рекурсия" = "KeywordTailrec"
"чистый" = "KeywordPure"
"использует" = "KeywordUses"
"обработать" = "KeywordHandle"
"с" = "KeywordWith"
"требует" = "KeywordRequires"
"обеспечивает" = "KeywordEnsures"
"инвариант" = "KeywordInvariant"
