name = "Russian"
description = "Russian Control Flow Keywords"

[keywords]
"функция" = "KeywordFun"
"если" = "KeywordIf"
"иначе" = "KeywordElse"
"пока" = "KeywordWhile"
"для" = "KeywordFor"
"в" = "KeywordIn"
"совпадение" = "KeywordMatch"
"прервать" = "KeywordBreak"
"продолжить" = "KeywordContinue"
"вернуть" = "KeywordReturn"
"когда" = "KeywordWhen"
"попробовать" = "KeywordTry"
"поймать" = "KeywordCatch"
"наконец" = "KeywordFinally"
"бросить" = "KeywordThrow"
"цикл" = "KeywordLoop"
"отложить" = "KeywordDefer"
"утверждать" = "KeywordAssert"
