name = "Russian"
description = "Russian Type Definition Keywords"

[keywords]
"структура" = "KeywordStruct"
"перечисление" = "KeywordEnum"
"черта" = "KeywordSpec"
"реализовать" = "KeywordImpl"
"тип" = "KeywordType"
"класс" = "KeywordClass"
"запечатанный" = "KeywordSealed"
"объект" = "KeywordObject"
"интерфейс" = "KeywordInterface"
"открытый" = "KeywordOpen"
"финальный" = "KeywordFinal"
"абстрактный" = "KeywordAbstract"
"переопределить" = "KeywordOverride"
"поздняя_инициализация" = "KeywordLateinit"
"компаньон" = "KeywordCompanion"
"расширение" = "KeywordExtension"
"трейт" = "KeywordTrait"
"данные" = "KeywordData"
"расширяет" = "KeywordExtends"
"различный" = "KeywordDistinct"
"объединение" = "KeywordUnion"
