# German language configuration for the Seen programming language
# Deutsche Sprachkonfiguration für die Seen-Programmiersprache

name = "German"
description = "German keyword set for the Seen programming language - Deutsche Schlüsselwörter für die Seen-Programmiersprache"

[keywords]
"funktion" = "KeywordFun"
"wenn" = "KeywordIf"
"sonst" = "KeywordElse"
"während" = "KeywordWhile"
"für" = "KeywordFor"
"in" = "KeywordIn"
"übereinstimmen" = "KeywordMatch"
"brechen" = "KeywordBreak"
"fortsetzen" = "KeywordContinue"
"zurückgeben" = "KeywordReturn"
"wann" = "KeywordWhen"
"sei" = "KeywordLet"
"wert" = "KeywordVal"
"variable" = "KeywordVar"
"veränderlich" = "KeywordMut"
"konstante" = "KeywordConst"
"statisch" = "KeywordStatic"
"struktur" = "KeywordStruct"
"aufzählung" = "KeywordEnum"
"eigenschaft" = "KeywordTrait"
"implementieren" = "KeywordImpl"
"typ" = "KeywordType"
"klasse" = "KeywordClass"
"daten" = "KeywordData"
"versiegelt" = "KeywordSealed"
"objekt" = "KeywordObject"
"schnittstelle" = "KeywordInterface"
"modul" = "KeywordModule"
"importieren" = "KeywordImport"
"verwenden" = "KeywordUse"
"wahr" = "KeywordTrue"
"falsch" = "KeywordFalse"
"null" = "KeywordNull"
"ist" = "KeywordIs"
"als" = "KeywordAs"
"durch" = "KeywordBy"
"aussetzen" = "KeywordSuspend"
"warten" = "KeywordAwait"
"starten" = "KeywordLaunch"
"fluss" = "KeywordFlow"
"versuchen" = "KeywordTry"
"fangen" = "KeywordCatch"
"schließlich" = "KeywordFinally"
"werfen" = "KeywordThrow"
"inline" = "KeywordInline"
"reifiziert" = "KeywordReified"
"kreuzinline" = "KeywordCrossinline"
"kein_inline" = "KeywordNoinline"
"operator" = "KeywordOperator"
"infix" = "KeywordInfix"
"schwanz_rekursion" = "KeywordTailrec"
"offen" = "KeywordOpen"
"final" = "KeywordFinal"
"abstrakt" = "KeywordAbstract"
"überschreiben" = "KeywordOverride"
"spät_init" = "KeywordLateinit"
"begleiter" = "KeywordCompanion"
"und" = "KeywordAnd"
"oder" = "KeywordOr"
"nicht" = "KeywordNot"
"bewegen" = "KeywordMove"
"ausleihen" = "KeywordBorrow"
"an_ort" = "KeywordInout"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"
"@" = "At"