# English language configuration for the Seen programming language

name = "English"
description = "English keyword set for the Seen programming language"

[keywords]
"fun" = "KeywordFun"
"if" = "KeywordIf"
"else" = "KeywordElse"
"while" = "KeywordWhile"
"for" = "KeywordFor"
"in" = "KeywordIn"
"match" = "KeywordMatch"
"break" = "KeywordBreak"
"continue" = "KeywordContinue"
"return" = "KeywordReturn"
"let" = "KeywordLet"
"mut" = "KeywordMut"
"const" = "KeywordConst"
"static" = "KeywordStatic"
"struct" = "KeywordStruct"
"enum" = "KeywordEnum"
"trait" = "KeywordTrait"
"impl" = "KeywordImpl"
"type" = "KeywordType"
"module" = "KeywordModule"
"import" = "KeywordImport"
"use" = "KeywordUse"
"true" = "KeywordTrue"
"false" = "KeywordFalse"
"null" = "KeywordNull"
"val" = "KeywordVal"
"var" = "KeywordVar"
"async" = "KeywordAsync"
"suspend" = "KeywordSuspend"
"await" = "KeywordAwait"
"launch" = "KeywordLaunch"
"flow" = "KeywordFlow"
"try" = "KeywordTry"
"catch" = "KeywordCatch"
"finally" = "KeywordFinally"
"throw" = "KeywordThrow"
"class" = "KeywordClass"
"inline" = "KeywordInline"
"reified" = "KeywordReified"
"crossinline" = "KeywordCrossinline"
"noinline" = "KeywordNoinline"
"data" = "KeywordData"
"sealed" = "KeywordSealed"
"object" = "KeywordObject"
"interface" = "KeywordInterface"
"open" = "KeywordOpen"
"final" = "KeywordFinal"
"abstract" = "KeywordAbstract"
"override" = "KeywordOverride"
"lateinit" = "KeywordLateinit"
"companion" = "KeywordCompanion"
"operator" = "KeywordOperator"
"infix" = "KeywordInfix"
"tailrec" = "KeywordTailrec"
"when" = "KeywordWhen"
"is" = "KeywordIs"
"as" = "KeywordAs"
"by" = "KeywordBy"
"and" = "KeywordAnd"
"or" = "KeywordOr"
"not" = "KeywordNot"
"move" = "KeywordMove"
"borrow" = "KeywordBorrow"
"inout" = "KeywordInout"
"region" = "KeywordRegion"
"arena" = "KeywordArena"
"comptime" = "KeywordComptime"
"macro" = "KeywordMacro"
"spawn" = "KeywordSpawn"
"select" = "KeywordSelect"
"actor" = "KeywordActor"
"receive" = "KeywordReceive"
"send" = "KeywordSend"
"to" = "KeywordTo"
"from" = "KeywordFrom"
"request" = "KeywordRequest"
"reply" = "KeywordReply"
"observable" = "KeywordObservable"
"emit" = "KeywordEmit"
"delay" = "KeywordDelay"
"effect" = "KeywordEffect"
"pure" = "KeywordPure"
"uses" = "KeywordUses"
"handle" = "KeywordHandle"
"with" = "KeywordWith"
"requires" = "KeywordRequires"
"ensures" = "KeywordEnsures"
"invariant" = "KeywordInvariant"
"defer" = "KeywordDefer"
"assert" = "KeywordAssert"
"extension" = "KeywordExtension"
"loop" = "KeywordLoop"
"external" = "KeywordExternal"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"