# English language configuration for the Seen programming language

name = "English"
description = "English keyword set for the Seen programming language"

[keywords]
"fun" = "KeywordFun"
"if" = "KeywordIf"
"else" = "KeywordElse"
"while" = "KeywordWhile"
"for" = "KeywordFor"
"in" = "KeywordIn"
"match" = "KeywordMatch"
"break" = "KeywordBreak"
"continue" = "KeywordContinue"
"return" = "KeywordReturn"
"let" = "KeywordLet"
"mut" = "KeywordMut"
"const" = "KeywordConst"
"static" = "KeywordStatic"
"struct" = "KeywordStruct"
"enum" = "KeywordEnum"
"trait" = "KeywordTrait"
"impl" = "KeywordImpl"
"type" = "KeywordType"
"module" = "KeywordModule"
"import" = "KeywordImport"
"pub" = "KeywordPub"
"priv" = "KeywordPriv"
"true" = "KeywordTrue"
"false" = "KeywordFalse"
"val" = "KeywordVal"
"var" = "KeywordVar"
"suspend" = "KeywordSuspend"
"await" = "KeywordAwait"
"launch" = "KeywordLaunch"
"flow" = "KeywordFlow"
"try" = "KeywordTry"
"catch" = "KeywordCatch"
"finally" = "KeywordFinally"
"throw" = "KeywordThrow"
"class" = "KeywordClass"
"inline" = "KeywordInline"
"reified" = "KeywordReified"
"crossinline" = "KeywordCrossinline"
"noinline" = "KeywordNoinline"
"data" = "KeywordData"
"sealed" = "KeywordSealed"
"object" = "KeywordObject"
"interface" = "KeywordInterface"
"open" = "KeywordOpen"
"final" = "KeywordFinal"
"abstract" = "KeywordAbstract"
"override" = "KeywordOverride"
"lateinit" = "KeywordLateinit"
"companion" = "KeywordCompanion"
"operator" = "KeywordOperator"
"infix" = "KeywordInfix"
"tailrec" = "KeywordTailrec"
"when" = "KeywordWhen"
"is" = "KeywordIs"
"as" = "KeywordAs"
"by" = "KeywordBy"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&&" = "LogicalAnd"
"||" = "LogicalOr"
"!" = "LogicalNot"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"