# Spanish language configuration for the Seen programming language
# Configuración del idioma español para el lenguaje de programación Seen

name = "Spanish"
description = "Spanish keyword set for the Seen programming language - Conjunto de palabras clave en español para el lenguaje de programación Seen"

[keywords]
# Control flow - Control de flujo
"función" = "KeywordFun"        # function
"si" = "KeywordIf"              # if
"sino" = "KeywordElse"          # else
"mientras" = "KeywordWhile"     # while
"para" = "KeywordFor"           # for
"en" = "KeywordIn"              # in
"coincidir" = "KeywordMatch"    # match
"romper" = "KeywordBreak"       # break
"continuar" = "KeywordContinue" # continue
"retornar" = "KeywordReturn"    # return
"cuando" = "KeywordWhen"        # when

# Variable declarations - Declaraciones de variables
"sea" = "KeywordLet"            # let
"valor" = "KeywordVal"          # val
"variable" = "KeywordVar"       # var
"mutable" = "KeywordMut"        # mutable
"constante" = "KeywordConst"    # const
"estático" = "KeywordStatic"    # static

# Type definitions - Definiciones de tipos
"estructura" = "KeywordStruct"  # struct
"enumeración" = "KeywordEnum"   # enum
"rasgo" = "KeywordTrait"        # trait
"implementar" = "KeywordImpl"   # impl
"tipo" = "KeywordType"          # type
"clase" = "KeywordClass"        # class
"datos" = "KeywordData"         # data
"sellado" = "KeywordSealed"     # sealed
"objeto" = "KeywordObject"      # object
"interfaz" = "KeywordInterface" # interface

# Module system - Sistema de módulos
"módulo" = "KeywordModule"      # module
"importar" = "KeywordImport"    # import
"usar" = "KeywordUse"           # use

# Literals - Literales
"verdadero" = "KeywordTrue"     # true
"falso" = "KeywordFalse"        # false
"nulo" = "KeywordNull"          # null

# Type checking - Verificación de tipos
"es" = "KeywordIs"              # is
"como" = "KeywordAs"            # as
"por" = "KeywordBy"             # by

# Async/Coroutines - Asíncrono/Corrutinas
"asíncrono" = "KeywordAsync"    # async
"suspender" = "KeywordSuspend"  # suspend
"esperar" = "KeywordAwait"      # await
"lanzar" = "KeywordLaunch"      # launch
"flujo" = "KeywordFlow"         # flow

# Error handling - Manejo de errores
"intentar" = "KeywordTry"       # try
"capturar" = "KeywordCatch"     # catch
"finalmente" = "KeywordFinally" # finally
"lanzar_error" = "KeywordThrow" # throw

# Function modifiers - Modificadores de función
"en_línea" = "KeywordInline"    # inline
"reificado" = "KeywordReified"  # reified
"línea_cruzada" = "KeywordCrossinline" # crossinline
"sin_línea" = "KeywordNoinline" # noinline
"operador" = "KeywordOperator"  # operator
"infijo" = "KeywordInfix"       # infix
"cola_recursiva" = "KeywordTailrec" # tailrec

# Class modifiers - Modificadores de clase
"abierto" = "KeywordOpen"       # open
"final" = "KeywordFinal"        # final
"abstracto" = "KeywordAbstract" # abstract
"anular" = "KeywordOverride"    # override
"init_tardío" = "KeywordLateinit" # lateinit
"compañero" = "KeywordCompanion" # companion

# Logical operators - Operadores lógicos
"y" = "KeywordAnd"              # and
"o" = "KeywordOr"               # or
"no" = "KeywordNot"             # not

# Memory management - Gestión de memoria
"mover" = "KeywordMove"         # move
"prestar" = "KeywordBorrow"     # borrow
"en_lugar" = "KeywordInout"     # inout

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"
"@" = "At"