# Hindi language configuration for the Seen programming language
# सीन प्रोग्रामिंग भाषा के लिए हिंदी भाषा कॉन्फ़िगरेशन

name = "Hindi"
description = "Hindi keyword set for the Seen programming language - सीन प्रोग्रामिंग भाषा के लिए हिंदी कीवर्ड सेट"

[keywords]
"फ़ंक्शन" = "KeywordFun"
"अगर" = "KeywordIf"
"नहीं_तो" = "KeywordElse"
"जब_तक" = "KeywordWhile"
"के_लिए" = "KeywordFor"
"में" = "KeywordIn"
"मिलान" = "KeywordMatch"
"तोड़ना" = "KeywordBreak"
"जारी_रखना" = "KeywordContinue"
"वापस_करना" = "KeywordReturn"
"कब" = "KeywordWhen"
"होने_दो" = "KeywordLet"
"मान" = "KeywordVal"
"चर" = "KeywordVar"
"परिवर्तनीय" = "KeywordMut"
"स्थिरांक" = "KeywordConst"
"स्थैतिक" = "KeywordStatic"
"संरचना" = "KeywordStruct"
"गणना" = "KeywordEnum"
"गुण" = "KeywordTrait"
"लागू_करना" = "KeywordImpl"
"प्रकार" = "KeywordType"
"वर्ग" = "KeywordClass"
"डेटा" = "KeywordData"
"सीलबंद" = "KeywordSealed"
"वस्तु" = "KeywordObject"
"इंटरफ़ेस" = "KeywordInterface"
"मॉड्यूल" = "KeywordModule"
"आयात" = "KeywordImport"
"उपयोग" = "KeywordUse"
"सच" = "KeywordTrue"
"झूठ" = "KeywordFalse"
"शून्य" = "KeywordNull"
"है" = "KeywordIs"
"के_रूप_में" = "KeywordAs"
"द्वारा" = "KeywordBy"
"अतुल्यकालिक" = "KeywordAsync"
"निलंबित" = "KeywordSuspend"
"प्रतीक्षा" = "KeywordAwait"
"लॉन्च" = "KeywordLaunch"
"प्रवाह" = "KeywordFlow"
"कोशिश" = "KeywordTry"
"पकड़ना" = "KeywordCatch"
"अंत_में" = "KeywordFinally"
"फेंकना" = "KeywordThrow"
"इनलाइन" = "KeywordInline"
"मूर्त" = "KeywordReified"
"क्रॉस_इनलाइन" = "KeywordCrossinline"
"गैर_इनलाइन" = "KeywordNoinline"
"ऑपरेटर" = "KeywordOperator"
"इन्फिक्स" = "KeywordInfix"
"पूंछ_रिकर्सन" = "KeywordTailrec"
"खुला" = "KeywordOpen"
"अंतिम" = "KeywordFinal"
"अमूर्त" = "KeywordAbstract"
"ओवरराइड" = "KeywordOverride"
"देर_से_इनिट" = "KeywordLateinit"
"साथी" = "KeywordCompanion"
"और" = "KeywordAnd"
"या" = "KeywordOr"
"नहीं" = "KeywordNot"
"स्थानांतरित" = "KeywordMove"
"उधार" = "KeywordBorrow"
"स्थान_पर" = "KeywordInout"
"क्षेत्र" = "KeywordRegion"
"अखाड़ा" = "KeywordArena"
"जन्म" = "KeywordSpawn"
"चयन" = "KeywordSelect"
"अभिनेता" = "KeywordActor"
"प्राप्त" = "KeywordReceive"
"भेजना" = "KeywordSend"
"को" = "KeywordTo"
"से" = "KeywordFrom"
"अनुरोध" = "KeywordRequest"
"उत्तर" = "KeywordReply"
"अवलोकनीय" = "KeywordObservable"
"उत्सर्जन" = "KeywordEmit"
"देरी" = "KeywordDelay"
"प्रभाव" = "KeywordEffect"
"शुद्ध" = "KeywordPure"
"प्रयोग" = "KeywordUses"
"संभालना" = "KeywordHandle"
"साथ" = "KeywordWith"
"आवश्यकता" = "KeywordRequires"
"सुनिश्चित" = "KeywordEnsures"
"अपरिवर्तनीय" = "KeywordInvariant"
"स्थगित" = "KeywordDefer"
"दावा" = "KeywordAssert"
"विस्तार" = "KeywordExtension"
"लूप" = "KeywordLoop"
"बाहरी" = "KeywordExternal"
"संकलन_समय" = "KeywordComptime"
"मैक्रो" = "KeywordMacro"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"
"@" = "At"