# Portuguese language configuration for the Seen programming language
# Configuração da língua portuguesa para a linguagem de programação Seen

name = "Portuguese"
description = "Portuguese keyword set for the Seen programming language - Conjunto de palavras-chave em português para a linguagem de programação Seen"

[keywords]
"função" = "KeywordFun"
"se" = "KeywordIf"
"senão" = "KeywordElse"
"enquanto" = "KeywordWhile"
"para" = "KeywordFor"
"em" = "KeywordIn"
"corresponder" = "KeywordMatch"
"quebrar" = "KeywordBreak"
"continuar" = "KeywordContinue"
"retornar" = "KeywordReturn"
"quando" = "KeywordWhen"
"seja" = "KeywordLet"
"valor" = "KeywordVal"
"variável" = "KeywordVar"
"mutável" = "KeywordMut"
"constante" = "KeywordConst"
"estático" = "KeywordStatic"
"estrutura" = "KeywordStruct"
"enumeração" = "KeywordEnum"
"traço" = "KeywordTrait"
"implementar" = "KeywordImpl"
"tipo" = "KeywordType"
"classe" = "KeywordClass"
"dados" = "KeywordData"
"selado" = "KeywordSealed"
"objeto" = "KeywordObject"
"interface" = "KeywordInterface"
"módulo" = "KeywordModule"
"importar" = "KeywordImport"
"usar" = "KeywordUse"
"verdadeiro" = "KeywordTrue"
"falso" = "KeywordFalse"
"nulo" = "KeywordNull"
"é" = "KeywordIs"
"como" = "KeywordAs"
"por" = "KeywordBy"
"assíncrono" = "KeywordAsync"
"suspender" = "KeywordSuspend"
"aguardar" = "KeywordAwait"
"lançar" = "KeywordLaunch"
"fluxo" = "KeywordFlow"
"tentar" = "KeywordTry"
"capturar" = "KeywordCatch"
"finalmente" = "KeywordFinally"
"lançar_erro" = "KeywordThrow"
"em_linha" = "KeywordInline"
"reificado" = "KeywordReified"
"linha_cruzada" = "KeywordCrossinline"
"sem_linha" = "KeywordNoinline"
"operador" = "KeywordOperator"
"infixo" = "KeywordInfix"
"recursão_cauda" = "KeywordTailrec"
"aberto" = "KeywordOpen"
"final" = "KeywordFinal"
"abstrato" = "KeywordAbstract"
"sobrescrever" = "KeywordOverride"
"init_tardio" = "KeywordLateinit"
"companheiro" = "KeywordCompanion"
"e" = "KeywordAnd"
"ou" = "KeywordOr"
"não" = "KeywordNot"
"mover" = "KeywordMove"
"emprestar" = "KeywordBorrow"
"no_local" = "KeywordInout"
"região" = "KeywordRegion"
"arena" = "KeywordArena"
"gerar" = "KeywordSpawn"
"selecionar" = "KeywordSelect"
"ator" = "KeywordActor"
"receber" = "KeywordReceive"
"enviar" = "KeywordSend"
"até" = "KeywordTo"
"de" = "KeywordFrom"
"solicitar" = "KeywordRequest"
"responder" = "KeywordReply"
"observável" = "KeywordObservable"
"emitir" = "KeywordEmit"
"atrasar" = "KeywordDelay"
"efeito" = "KeywordEffect"
"puro" = "KeywordPure"
"usa" = "KeywordUses"
"lidar" = "KeywordHandle"
"com" = "KeywordWith"
"requer" = "KeywordRequires"
"garante" = "KeywordEnsures"
"invariante" = "KeywordInvariant"
"adiar" = "KeywordDefer"
"afirmar" = "KeywordAssert"
"extensão" = "KeywordExtension"
"laço" = "KeywordLoop"
"externo" = "KeywordExternal"
"tempo_compilação" = "KeywordComptime"
"macro" = "KeywordMacro"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"
"@" = "At"