# Russian language configuration for the Seen programming language
# Конфигурация русского языка для языка программирования Seen

name = "Russian"
description = "Russian keyword set for the Seen programming language - Набор русских ключевых слов для языка программирования Seen"

[keywords]
"функция" = "KeywordFun"
"если" = "KeywordIf"
"иначе" = "KeywordElse"
"пока" = "KeywordWhile"
"для" = "KeywordFor"
"в" = "KeywordIn"
"совпадение" = "KeywordMatch"
"прервать" = "KeywordBreak"
"продолжить" = "KeywordContinue"
"вернуть" = "KeywordReturn"
"когда" = "KeywordWhen"
"пусть" = "KeywordLet"
"значение" = "KeywordVal"
"переменная" = "KeywordVar"
"изменяемый" = "KeywordMut"
"константа" = "KeywordConst"
"статический" = "KeywordStatic"
"структура" = "KeywordStruct"
"перечисление" = "KeywordEnum"
"черта" = "KeywordTrait"
"реализовать" = "KeywordImpl"
"тип" = "KeywordType"
"класс" = "KeywordClass"
"данные" = "KeywordData"
"запечатанный" = "KeywordSealed"
"объект" = "KeywordObject"
"интерфейс" = "KeywordInterface"
"модуль" = "KeywordModule"
"импортировать" = "KeywordImport"
"использовать" = "KeywordUse"
"истина" = "KeywordTrue"
"ложь" = "KeywordFalse"
"ноль" = "KeywordNull"
"является" = "KeywordIs"
"как" = "KeywordAs"
"через" = "KeywordBy"
"асинхронный" = "KeywordAsync"
"приостановить" = "KeywordSuspend"
"ждать" = "KeywordAwait"
"запустить" = "KeywordLaunch"
"поток" = "KeywordFlow"
"попробовать" = "KeywordTry"
"поймать" = "KeywordCatch"
"наконец" = "KeywordFinally"
"бросить" = "KeywordThrow"
"встроенный" = "KeywordInline"
"овеществленный" = "KeywordReified"
"перекрестно_встроенный" = "KeywordCrossinline"
"не_встроенный" = "KeywordNoinline"
"оператор" = "KeywordOperator"
"инфиксный" = "KeywordInfix"
"хвостовая_рекурсия" = "KeywordTailrec"
"открытый" = "KeywordOpen"
"финальный" = "KeywordFinal"
"абстрактный" = "KeywordAbstract"
"переопределить" = "KeywordOverride"
"поздняя_инициализация" = "KeywordLateinit"
"компаньон" = "KeywordCompanion"
"и" = "KeywordAnd"
"или" = "KeywordOr"
"не" = "KeywordNot"
"переместить" = "KeywordMove"
"заимствовать" = "KeywordBorrow"
"на_месте" = "KeywordInout"
"регион" = "KeywordRegion"
"арена" = "KeywordArena"
"породить" = "KeywordSpawn"
"выбрать" = "KeywordSelect"
"актёр" = "KeywordActor"
"получить" = "KeywordReceive"
"отправить" = "KeywordSend"
"запросить" = "KeywordRequest"
"ответить" = "KeywordReply"
"наблюдаемый" = "KeywordObservable"
"излучить" = "KeywordEmit"
"задержать" = "KeywordDelay"
"эффект" = "KeywordEffect"
"чистый" = "KeywordPure"
"использует" = "KeywordUses"
"обработать" = "KeywordHandle"
"с" = "KeywordWith"
"требует" = "KeywordRequires"
"обеспечивает" = "KeywordEnsures"
"инвариант" = "KeywordInvariant"
"отложить" = "KeywordDefer"
"утверждать" = "KeywordAssert"
"расширение" = "KeywordExtension"
"цикл" = "KeywordLoop"
"внешний" = "KeywordExternal"
"время_компиляции" = "KeywordComptime"
"макрос" = "KeywordMacro"

[operators]
"+" = "Plus"
"-" = "Minus"
"*" = "Multiply"
"/" = "Divide"
"%" = "Modulo"
"=" = "Assign"
"+=" = "PlusAssign"
"-=" = "MinusAssign"
"*=" = "MultiplyAssign"
"/=" = "DivideAssign"
"%=" = "ModuloAssign"
"==" = "Equal"
"!=" = "NotEqual"
"<" = "Less"
"<=" = "LessEqual"
">" = "Greater"
">=" = "GreaterEqual"
"&" = "BitwiseAnd"
"|" = "BitwiseOr"
"^" = "BitwiseXor"
"~" = "BitwiseNot"
"<<" = "LeftShift"
">>" = "RightShift"
"->" = "Arrow"
"=>" = "FatArrow"
"?" = "Question"
"." = "Dot"
".." = "DotDot"
"..." = "TripleDot"
"..<" = "DotDotLess"
"::" = "DoubleColon"
"?." = "QuestionDot"
"?:" = "Elvis"
"!!" = "BangBang"
"_" = "Underscore"
"@" = "At"