name = "Arabic"
description = "Arabic Memory Management Keywords"

[keywords]
"انقل" = "KeywordMove"
"استعر" = "KeywordBorrow"
"في_المكان" = "KeywordInout"
"منطقة" = "KeywordRegion"
"حلبة" = "KeywordArena"
