name = "Arabic"
description = "Arabic Control Flow Keywords"

[keywords]
"دالة" = "KeywordFun"
"إذا" = "KeywordIf"
"وإلا" = "KeywordElse"
"بينما" = "KeywordWhile"
"لكل" = "KeywordFor"
"في" = "KeywordIn"
"طابق" = "KeywordMatch"
"اكسر" = "KeywordBreak"
"استمر" = "KeywordContinue"
"رجع" = "KeywordReturn"
"عندما" = "KeywordWhen"
"جرب" = "KeywordTry"
"امسك" = "KeywordCatch"
"أخيرا" = "KeywordFinally"
"ارم" = "KeywordThrow"
"حلقة" = "KeywordLoop"
"أجل" = "KeywordDefer"
"أكد" = "KeywordAssert"
"غير_آمن" = "KeywordUnsafe"
"أجل_خطأ" = "KeywordErrdefer"
