name = "Arabic"
description = "Arabic Async and Concurrency Keywords"

[keywords]
"غير_متزامن" = "KeywordAsync"
"علق" = "KeywordSuspend"
"انتظر" = "KeywordAwait"
"شغل" = "KeywordLaunch"
"تدفق" = "KeywordFlow"
"ولد" = "KeywordSpawn"
"اختر" = "KeywordSelect"
"ممثل" = "KeywordActor"
"استقبل" = "KeywordReceive"
"أرسل" = "KeywordSend"
"parallel_for" = "KeywordParallelFor"
"نطاق" = "KeywordScope"
"الغاء" = "KeywordCancel"
"منفصل" = "KeywordDetached"
"طلب" = "KeywordRequest"
"رد" = "KeywordReply"
"قابل_المراقبة" = "KeywordObservable"
"اصدر" = "KeywordEmit"
"أخر" = "KeywordDelay"
