name = "Arabic"
description = "Arabic Modifier Keywords"

[keywords]
"مضمن" = "KeywordInline"
"محقق" = "KeywordReified"
"مضمن_متقاطع" = "KeywordCrossinline"
"غير_مضمن" = "KeywordNoinline"
"مشغل" = "KeywordOperator"
"ثابت_وسط" = "KeywordInfix"
"عودة_ذيل" = "KeywordTailrec"
"نقي" = "KeywordPure"
"يستخدم" = "KeywordUses"
"تعامل" = "KeywordHandle"
"مع" = "KeywordWith"
"يتطلب" = "KeywordRequires"
"يضمن" = "KeywordEnsures"
"غير_متغير" = "KeywordInvariant"
"عام" = "KeywordPub"
"قابل_للتغيير" = "KeywordMut"
"ساكن" = "KeywordStatic"
