name = "Chinese"
description = "Chinese Control Flow Keywords"

[keywords]
"函数" = "KeywordFun"
"如果" = "KeywordIf"
"否则" = "KeywordElse"
"当" = "KeywordWhile"
"对于" = "KeywordFor"
"在" = "KeywordIn"
"匹配" = "KeywordMatch"
"中断" = "KeywordBreak"
"继续" = "KeywordContinue"
"返回" = "KeywordReturn"
"当时" = "KeywordWhen"
"尝试" = "KeywordTry"
"捕获" = "KeywordCatch"
"最终" = "KeywordFinally"
"抛出" = "KeywordThrow"
"循环" = "KeywordLoop"
"延迟" = "KeywordDefer"
"断言" = "KeywordAssert"
"不安全" = "KeywordUnsafe"
"错误延迟" = "KeywordErrdefer"
