name = "Chinese"
description = "Chinese Type Definition Keywords"

[keywords]
"数据" = "KeywordData"
"结构" = "KeywordStruct"
"枚举" = "KeywordEnum"
"规范" = "KeywordSpec"
"实现" = "KeywordImpl"
"类型" = "KeywordType"
"类" = "KeywordClass"
"密封" = "KeywordSealed"
"对象" = "KeywordObject"
"接口" = "KeywordInterface"
"开放" = "KeywordOpen"
"最终的" = "KeywordFinal"
"抽象" = "KeywordAbstract"
"重写" = "KeywordOverride"
"延迟初始化" = "KeywordLateinit"
"伴生" = "KeywordCompanion"
"扩展" = "KeywordExtension"
"特征" = "KeywordTrait"
"继承" = "KeywordExtends"
"独特" = "KeywordDistinct"
"联合" = "KeywordUnion"
