name = "Chinese"
description = "Chinese Modifier Keywords"

[keywords]
"内联" = "KeywordInline"
"具体化" = "KeywordReified"
"交叉内联" = "KeywordCrossinline"
"非内联" = "KeywordNoinline"
"运算符" = "KeywordOperator"
"中缀" = "KeywordInfix"
"尾递归" = "KeywordTailrec"
"纯" = "KeywordPure"
"运用" = "KeywordUses"
"处理" = "KeywordHandle"
"与" = "KeywordWith"
"要求" = "KeywordRequires"
"确保" = "KeywordEnsures"
"不变量" = "KeywordInvariant"
"公开" = "KeywordPub"
"可变" = "KeywordMut"
"常量" = "KeywordConst"
"静态" = "KeywordStatic"
