[package]
name = "seen_common"
version = "0.1.0"
edition = "2021"
description = "Common utilities and shared functionality for the Seen programming language"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"
