name = "Japanese"
description = "Japanese Modifier Keywords"

[keywords]
"インライン" = "KeywordInline"
"具体化" = "KeywordReified"
"クロスインライン" = "KeywordCrossinline"
"非インライン" = "KeywordNoinline"
"演算子" = "KeywordOperator"
"中置" = "KeywordInfix"
"末尾再帰" = "KeywordTailrec"
"純粋" = "KeywordPure"
"利用" = "KeywordUses"
"処理" = "KeywordHandle"
"付き" = "KeywordWith"
"要求" = "KeywordRequires"
"保証" = "KeywordEnsures"
"不変条件" = "KeywordInvariant"
"公開" = "KeywordPub"
"可変" = "KeywordMut"
"静的" = "KeywordStatic"
