name = "Japanese"
description = "Japanese Control Flow Keywords"

[keywords]
"関数" = "KeywordFun"
"もし" = "KeywordIf"
"そうでなければ" = "KeywordElse"
"間" = "KeywordWhile"
"のために" = "KeywordFor"
"で" = "KeywordIn"
"一致" = "KeywordMatch"
"中止" = "KeywordBreak"
"継続" = "KeywordContinue"
"戻る" = "KeywordReturn"
"場合" = "KeywordWhen"
"試行" = "KeywordTry"
"捕捉" = "KeywordCatch"
"最後に" = "KeywordFinally"
"投げる" = "KeywordThrow"
"繰返" = "KeywordLoop"
"延期" = "KeywordDefer"
"表明" = "KeywordAssert"
"安全でない" = "KeywordUnsafe"
"エラー延期" = "KeywordErrdefer"
