name = "ja"
description = "English Control Flow Keywords"

[keywords]
"fun" = "KeywordFun"
"if" = "KeywordIf"
"else" = "KeywordElse"
"while" = "KeywordWhile"
"for" = "KeywordFor"
"in" = "KeywordIn"
"match" = "KeywordMatch"
"break" = "KeywordBreak"
"continue" = "KeywordContinue"
"return" = "KeywordReturn"
"when" = "KeywordWhen"
"try" = "KeywordTry"
"catch" = "KeywordCatch"
"finally" = "KeywordFinally"
"throw" = "KeywordThrow"
"loop" = "KeywordLoop"
"defer" = "KeywordDefer"
"assert" = "KeywordAssert"
