name = "Japanese"
description = "Japanese Type Definition Keywords"

[keywords]
"データ" = "KeywordData"
"構造体" = "KeywordStruct"
"列挙" = "KeywordEnum"
"仕様" = "KeywordSpec"
"実装" = "KeywordImpl"
"型" = "KeywordType"
"クラス" = "KeywordClass"
"封印" = "KeywordSealed"
"オブジェクト" = "KeywordObject"
"インターフェース" = "KeywordInterface"
"開放" = "KeywordOpen"
"最終" = "KeywordFinal"
"抽象" = "KeywordAbstract"
"上書き" = "KeywordOverride"
"遅延初期化" = "KeywordLateinit"
"同伴" = "KeywordCompanion"
"拡張" = "KeywordExtension"
"トレイト" = "KeywordTrait"
"継承" = "KeywordExtends"
"独自" = "KeywordDistinct"
"共用体" = "KeywordUnion"
