# Arabic keywords for the Seen programming language

[language]
code = "ar"
name = "Arabic"
direction = "rtl"

[keywords]
val = "ثابت"       # thābit (constant)
var = "متغير"      # mutaghayyir (variable)
func = "دالة"      # dāllah (function)
if = "إذا"         # idhā (if)
else = "وإلا"      # wa-illā (otherwise)
while = "طالما"    # ṭālamā (as long as)
for = "لكل"        # likulli (for each)
return = "إرجاع"   # irjāʿ (return)
true = "صحيح"      # ṣaḥīḥ (true/correct)
false = "خطأ"      # khaṭaʾ (false/error)
null = "فارغ"      # fārigh (empty)
println = "اطبع"   # iṭbaʿ (print)
when = "عندما"     # ʿindamā (when)
in = "في"          # fī (in)
loop = "حلقة"      # ḥalaqah (loop)
break = "اخرج"     # ukhruj (exit)
continue = "استمر" # istamirr (continue)
struct = "هيكل"    # haykal (structure)
enum = "تعداد"     # tiʿdād (enumeration)
unsafe = "غير_آمن" # ghayr āmin (unsafe)
ref = "مرجع"       # marjiʿ (reference)
own = "ملك"        # milk (ownership)
async = "غير_متزامن" # ghayr mutazāmin (asynchronous)
await = "انتظر"    # intaẓir (wait)
