# English keywords for the Seen programming language

[language]
code = "en"
name = "English"
direction = "ltr"

[keywords]
val = "val"
var = "var"
func = "func"
if = "if"
else = "else"
while = "while"
for = "for"
return = "return"
true = "true"
false = "false"
null = "null"
println = "println"
when = "when"
in = "in"
loop = "loop"
break = "break"
continue = "continue"
struct = "struct"
enum = "enum"
unsafe = "unsafe"
ref = "ref"
own = "own"
async = "async"
await = "await"
