[package]
name = "arithmetic_bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "arithmetic_bench"
path = "arithmetic_bench.rs"

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1