[profile.default]
retries = 2
threads = "num-cpus"
test-threads = "num-cpus"

[profile.ci]
retries = 3
threads = 1
test-threads = 1
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.coverage]
retries = 0
threads = 1
test-threads = 1