#!/usr/bin/env python3
"""Fix LLVM IR codegen bugs from the frozen Seen compiler.

Applied to .ll files generated by the frozen bootstrap compiler when compiling
main.seen (the full CLI entry point).
"""

import re
import sys


def fix_declare_define_conflicts(content):
    """Remove `declare` lines when a `define` exists for the same function,
    and deduplicate multiple declares for the same function name."""
    defined = set()
    for m in re.finditer(r'^define\s+.*?@"?([A-Za-z0-9_.]+)"?\s*\(', content, re.MULTILINE):
        defined.add(m.group(1))

    # Collect call signatures to pick the right declare when duplicates exist
    call_sigs = {}  # fname → (ret_type, arg_count)
    for m in re.finditer(r'(?:call|invoke)\s+(\S+)\s+@"?([A-Za-z0-9_.]+)"?\s*\(([^)]*)\)', content):
        fname = m.group(2)
        ret = m.group(1)
        nargs = len([a for a in m.group(3).split(',') if a.strip()]) if m.group(3).strip() else 0
        call_sigs[fname] = (ret, nargs)

    lines = content.split('\n')
    out = []
    seen_declares = {}  # fname → (line_index, line_text)
    for i, line in enumerate(lines):
        if line.startswith('declare '):
            dm = re.search(r'@"?([A-Za-z0-9_.]+)"?\s*\(([^)]*)\)', line)
            if dm:
                fname = dm.group(1)
                if fname in defined:
                    continue  # Remove: define exists
                if fname in seen_declares:
                    # Duplicate declare — keep the one matching call sites
                    prev_idx, prev_line = seen_declares[fname]
                    if fname in call_sigs:
                        _, expected_nargs = call_sigs[fname]
                        prev_nargs = len([a for a in re.search(r'\(([^)]*)\)', prev_line).group(1).split(',') if a.strip()]) if re.search(r'\(([^)]*)\)', prev_line).group(1).strip() else 0
                        cur_nargs = len([a for a in dm.group(2).split(',') if a.strip()]) if dm.group(2).strip() else 0
                        if cur_nargs == expected_nargs and prev_nargs != expected_nargs:
                            # Current matches better — remove previous
                            out[prev_idx] = None
                            seen_declares[fname] = (len(out), line)
                            out.append(line)
                            continue
                    # Keep previous, skip current
                    continue
                seen_declares[fname] = (len(out), line)
        out.append(line)
    return '\n'.join(line for line in out if line is not None)


def fix_invalid_function_names(content):
    """Fix invalid LLVM function names."""
    # Remove define block for @<() (operator codegen bug)
    content = re.sub(r'define void @<\(\)[^\n]*\{[^}]*\}\n*', '', content)
    content = re.sub(r'; WARNING: unused function: <\n', '', content)

    # Quote function names with angle brackets: @Name<Type>_suffix → @"Name<Type>_suffix"
    def quote_angle_name(m):
        return '@"' + m.group(1) + '"' + m.group(2)

    content = re.sub(r'@([A-Za-z_]\w*<[^>]+>\w*)(\s*\()', quote_angle_name, content)
    return content


def fix_struct_zero(content):
    """Fix `%StructType 0` → `%StructType zeroinitializer` everywhere.

    The frozen compiler emits `0` instead of `zeroinitializer` for struct types.
    Matches named struct types (starting with uppercase letter) like %SeenString,
    %TypeNode, %SeenArray etc.
    """
    # Only match %Name where Name starts with uppercase (struct types)
    content = re.sub(r'(%[A-Z]\w*) 0\b(?!\d)', r'\1 zeroinitializer', content)

    # Fix bare `0` used as a type in declare/define parameter lists
    # e.g., declare void @func(i64, 0) → declare void @func(i64, i64)
    # Must NOT replace 0 in LLVM attributes like allocsize(0), allocsize(1) etc.
    def fix_param_zero(m):
        line = m.group(0)
        # Replace bare 0 as type (preceded by comma or open-paren, followed by comma or close-paren)
        # Negative lookbehind prevents matching allocsize(0) → allocsize(i64)
        line = re.sub(r'(?<!allocsize)([\(,]\s*)0(\s*[,\)])', r'\1i64\2', line)
        return line

    content = re.sub(r'^(declare|define)\s+.*$', fix_param_zero, content, flags=re.MULTILINE)
    return content


def fix_ptr_null(content):
    """Fix `ptr 0` → `ptr null` and `phi ptr [...], [ 0, ...]` → `[ null, ...]`."""
    # Direct ptr 0 → ptr null
    content = re.sub(r'\bptr 0\b(?![0-9xX])', 'ptr null', content)
    # In phi ptr: [ 0, %label ] → [ null, %label ]
    content = re.sub(r'(phi\s+ptr\s+(?:\[[^\]]*\],\s*)*\[)\s*0\s*,', r'\1 null,', content)
    return content


def fix_bare_string_refs(content, all_module_files=None):
    """Fix bare @.str.N references in modules.

    The frozen compiler sometimes emits bare @.str.N references (global counter)
    instead of module-prefixed @.str.MX.N. Two strategies:
    1. If @.str.MX.N exists in same module, rename the bare ref to use prefix
    2. Otherwise, generate an empty string constant as fallback
    """
    # Find the module prefix from defined string constants
    m = re.search(r'@\.str\.(M\d+)\.\d+\s*=', content)
    if not m:
        return content

    prefix = m.group(1)  # e.g., "M14"

    # Find all defined string constant numbers with the prefix
    defined = set()
    for dm in re.finditer(r'@\.str\.' + re.escape(prefix) + r'\.(\d+)\s*=', content):
        defined.add(dm.group(1))

    # Find all bare @.str.N references (not definitions)
    bare_refs = set()
    for bm in re.finditer(r'@\.str\.(?!M\d)(\d+)\b', content):
        bare_refs.add(bm.group(1))

    # Strategy 1: rename bare refs that have a matching MX.N definition
    def replace_bare(m):
        num = m.group(1)
        if num in defined:
            return f'@.str.{prefix}.{num}'
        return m.group(0)

    content = re.sub(r'@\.str\.(?!M\d)(\d+)\b', replace_bare, content)

    # Strategy 2: generate empty string constants for bare refs without MX.N match
    missing = bare_refs - defined
    if missing:
        # Try to find definitions from other module files
        other_defs = {}
        if all_module_files:
            for other_path in all_module_files:
                try:
                    with open(other_path) as f:
                        other_content = f.read()
                    for num in missing:
                        # Search for @.str.MX.N definition in other module
                        for dm in re.finditer(r'(@\.str\.M\d+\.' + num + r'\s*=\s*private unnamed_addr constant\s+\[[^\]]+\]\s+c"[^"]*")', other_content):
                            if num not in other_defs:
                                # Adapt the definition: change name to @.str.N
                                defn = dm.group(1)
                                defn = re.sub(r'@\.str\.M\d+\.', f'@.str.', defn)
                                other_defs[num] = defn
                except:
                    pass

        # Insert missing string constant definitions (skip if already defined)
        insert_defs = []
        for num in sorted(missing, key=int):
            # Check if @.str.N is already defined in the content
            if re.search(r'^@\.str\.' + num + r'\s*=', content, re.MULTILINE):
                continue
            if num in other_defs:
                insert_defs.append(other_defs[num])
            else:
                # Fallback: empty string
                insert_defs.append(f'@.str.{num} = private unnamed_addr constant [1 x i8] c"\\00"')

        if insert_defs:
            # Insert after the last @.str definition
            last_str = 0
            for sm in re.finditer(r'^@\.str\.\S+\s*=.*$', content, re.MULTILINE):
                last_str = sm.end()
            if last_str > 0:
                content = content[:last_str] + '\n' + '\n'.join(insert_defs) + content[last_str:]
            else:
                content = '\n'.join(insert_defs) + '\n' + content

    return content


def fix_undefined_symbols(content):
    """Add stub declarations for undefined functions and globals.

    Auto-detects undefined functions by scanning call sites vs declare/define,
    and generates stub declarations. Also adds external global declarations
    for undefined globals.
    """
    # Collect all called functions (both regular and quoted names)
    called = {}  # name → (ret_type, arg_types_str)
    for m in re.finditer(r'call\s+(\S+)\s+@"?([A-Za-z0-9_.<>]+)"?\s*\(([^)]*)\)', content):
        ret_type = m.group(1)
        fname = m.group(2)
        args = m.group(3)
        if fname not in called:
            called[fname] = (ret_type, args)

    # Also handle void calls: call void @func(...)
    for m in re.finditer(r'call\s+void\s+@"?([A-Za-z0-9_.<>]+)"?\s*\(([^)]*)\)', content):
        fname = m.group(1)
        if fname not in called:
            called[fname] = ('void', m.group(2))

    # Collect all declared/defined functions
    declared = set()
    for m in re.finditer(r'^(?:declare|define)\s+.*@"?([A-Za-z0-9_.<>]+)"?\s*\(', content, re.MULTILINE):
        declared.add(m.group(1))

    # Find undefined functions (exclude LLVM intrinsics)
    insert_lines = []
    for fname, (ret_type, args_str) in called.items():
        if fname in declared or fname.startswith('llvm.'):
            continue
        # Build stub declaration from call signature
        # Extract just the types from args
        arg_types = _extract_arg_types(args_str)
        arg_types_str = ', '.join(arg_types) if arg_types else ''

        # Quote name if it has special chars
        if '<' in fname or '>' in fname:
            qname = f'@"{fname}"'
        else:
            qname = f'@{fname}'

        insert_lines.append(f'declare {ret_type} {qname}({arg_types_str}) nounwind')

    # Check for undefined globals
    global_uses = set()
    for m in re.finditer(r'(?:load|store)\s+\S+.*?ptr\s+@([A-Za-z_]\w*)', content):
        global_uses.add(m.group(1))
    for gname in global_uses:
        if not re.search(r'^@' + re.escape(gname) + r'\s*=', content, re.MULTILINE):
            insert_lines.append(f'@{gname} = external global ptr')

    if insert_lines:
        lines = content.split('\n')
        insert_pos = 0
        for i, line in enumerate(lines):
            if line.startswith('declare ') or (line.startswith('@') and '=' in line):
                insert_pos = i + 1
        for j, stub in enumerate(insert_lines):
            lines.insert(insert_pos + j, stub)
        content = '\n'.join(lines)

    return content


def _extract_arg_types(args_str):
    """Extract just the types from a call argument string."""
    if not args_str.strip():
        return []
    args = _split_args(args_str)
    types = []
    for arg in args:
        a = arg.strip()
        if not a:
            continue
        # Match: TYPE VALUE or TYPE %reg or TYPE @global or TYPE literal
        m = re.match(r'(\S+)\s+', a)
        if m:
            types.append(m.group(1))
        else:
            types.append(a)
    return types


def fix_duplicate_globals(content):
    """Remove duplicate global variable declarations."""
    lines = content.split('\n')
    seen_globals = set()
    out = []
    for line in lines:
        m = re.match(r'^(@\w+)\s*=\s*(?:external\s+)?global', line)
        if m:
            gname = m.group(1)
            if gname in seen_globals:
                continue  # Skip duplicate
            seen_globals.add(gname)
        out.append(line)
    return '\n'.join(out)


def fix_ssa_numbering(content):
    """Fix out-of-order SSA register numbering within functions."""
    lines = content.split('\n')
    result = []
    func_start = -1
    func_buf = []

    for i, line in enumerate(lines):
        if re.match(r'^define\s+', line):
            func_start = i
            func_buf = [line]
            continue
        if func_start >= 0:
            func_buf.append(line)
            if line.strip() == '}':
                fixed = _fix_ssa_in_function(func_buf)
                result.extend(fixed)
                func_start = -1
                func_buf = []
            continue
        result.append(line)

    if func_buf:
        result.extend(func_buf)
    return '\n'.join(result)


def _fix_ssa_in_function(func_lines):
    """Fix SSA numbering in a single function."""
    body = '\n'.join(func_lines)

    # Find all %N definitions in order
    defs = [int(m.group(1)) for m in re.finditer(r'%(\d+)\s*=', body)]
    if not defs:
        return func_lines

    # Check monotonicity
    if all(defs[i] < defs[i+1] for i in range(len(defs)-1)):
        return func_lines

    # Build mapping preserving definition order
    seen = set()
    ordered = []
    for d in defs:
        if d not in seen:
            seen.add(d)
            ordered.append(d)

    start_num = min(ordered)
    mapping = {}
    for i, old_n in enumerate(ordered):
        mapping[old_n] = start_num + i

    if all(mapping[k] == k for k in mapping):
        return func_lines

    # Two-pass rename: % followed by number
    for old_n in sorted(mapping.keys(), reverse=True):
        new_n = mapping[old_n]
        if old_n != new_n:
            body = re.sub(r'%' + str(old_n) + r'(?=[\s,)};=]|$)',
                         f'%__R{new_n}__', body)

    body = re.sub(r'%__R(\d+)__', r'%\1', body)
    return body.split('\n')


def fix_type_mismatches(content):
    """Fix type mismatches by tracking register types per function.

    Runs multiple passes until convergence since fixing one mismatch
    can reveal another.
    """
    for iteration in range(5):  # Max 5 passes
        new_content = _fix_type_pass(content)
        if new_content == content:
            break
        content = new_content
    return content


def _fix_type_pass(content):
    """Single pass of type mismatch fixing."""
    lines = content.split('\n')
    result = []
    in_function = False
    func_buf = []

    for line in lines:
        if re.match(r'^define\s+', line):
            in_function = True
            func_buf = [line]
            continue
        if in_function:
            func_buf.append(line)
            if line.strip() == '}':
                fixed = _fix_function_types(func_buf)
                result.extend(fixed)
                in_function = False
                func_buf = []
            continue
        result.append(line)

    if func_buf:
        result.extend(func_buf)
    return '\n'.join(result)


def _get_reg_type(s, reg_types):
    """Parse a single line and extract register type definitions."""
    # %N = load TYPE, ...
    m = re.match(r'(%\d+)\s*=\s*load\s+(\S+)\s*,', s)
    if m: return m.group(1), m.group(2)

    # %N = call [attrs] TYPE @func(...)
    m = re.match(r'(%\d+)\s*=\s*(?:tail\s+)?call\s+(?:noalias\s+)?(?:dereferenceable\(\d+\)\s+)?(\S+)\s+@', s)
    if m: return m.group(1), m.group(2)

    # %N = insertvalue TYPE
    m = re.match(r'(%\d+)\s*=\s*insertvalue\s+(\S+)', s)
    if m: return m.group(1), m.group(2)

    # %N = alloca → ptr
    m = re.match(r'(%\d+)\s*=\s*alloca\s+', s)
    if m: return m.group(1), 'ptr'

    # %N = getelementptr → ptr
    m = re.match(r'(%\d+)\s*=\s*getelementptr\s+', s)
    if m: return m.group(1), 'ptr'

    # %N = icmp/fcmp → i1
    m = re.match(r'(%\d+)\s*=\s*[fi]cmp\s+', s)
    if m: return m.group(1), 'i1'

    # %N = arith TYPE
    m = re.match(r'(%\d+)\s*=\s*(?:add|sub|mul|sdiv|udiv|srem|urem|and|or|xor|shl|ashr|lshr)\s+(?:nuw\s+)?(?:nsw\s+)?(\S+)', s)
    if m: return m.group(1), m.group(2)

    # %N = cast ... to TYPE
    m = re.match(r'(%\d+)\s*=\s*(?:bitcast|trunc|zext|sext|ptrtoint|inttoptr|fpext|fptrunc|fptosi|sitofp|uitofp)\s+.*\s+to\s+(\S+)', s)
    if m: return m.group(1), m.group(2)

    # %N = select i1 %c, TYPE
    m = re.match(r'(%\d+)\s*=\s*select\s+i1\s+\S+,\s+(\S+)', s)
    if m: return m.group(1), m.group(2)

    # %N = phi TYPE
    m = re.match(r'(%\d+)\s*=\s*phi\s+(\S+)', s)
    if m: return m.group(1), m.group(2)

    return None, None


def _is_used_as_type(reg, expected_type, func_lines):
    """Check if register is used with a specific type in function (non-definition)."""
    reg_esc = re.escape(reg)
    et_esc = re.escape(expected_type)
    for line in func_lines:
        s = line.strip()
        if re.match(rf'{reg_esc}\s*=', s):
            continue
        # Direct type annotation: TYPE %N
        if re.search(rf'{et_esc}\s+{reg_esc}\b', line):
            if not re.match(rf'\s*{reg_esc}\s*=', s):
                return True
        # In phi: phi TYPE [ %N, ... ]
        if re.search(rf'phi\s+{et_esc}\s+.*{reg_esc}\b', line):
            return True
        # In store/call/ret with type
        if re.search(rf'(?:store|call|ret)\s+.*{et_esc}\s+{reg_esc}\b', line):
            return True
    return False


def _fix_function_types(func_lines):
    """Fix type mismatches within a single function."""
    # Build register types
    reg_types = {}
    for line in func_lines:
        reg, typ = _get_reg_type(line.strip(), reg_types)
        if reg:
            reg_types[reg] = typ

    # Get function return type
    func_ret_type = None
    hm = re.match(r'define\s+(?:noundef\s+)?(?:noalias\s+)?(?:dereferenceable\(\d+\)\s+)?(\S+)\s+@', func_lines[0])
    if hm:
        func_ret_type = hm.group(1)

    # Pass 1: Fix load types based on usage patterns
    pass1 = []
    for line in func_lines:
        fixed = line

        # load ptr → load %SeenString when used as %SeenString
        lm = re.match(r'(\s*%\d+\s*=\s*load\s+)(ptr)(,\s*ptr\s+\S+.*)', fixed)
        if lm:
            reg = re.match(r'\s*(%\d+)', fixed).group(1)
            if _is_used_as_type(reg, '%SeenString', func_lines):
                fixed = f'{lm.group(1)}%SeenString{lm.group(3)}'
                reg_types[reg] = '%SeenString'

        # load i64 → load ptr when used as ptr
        lm2 = re.match(r'(\s*%\d+\s*=\s*load\s+)(i64)(,\s*ptr\s+\S+.*)', fixed)
        if lm2:
            reg = re.match(r'\s*(%\d+)', fixed).group(1)
            if _is_used_as_type(reg, 'ptr', func_lines):
                fixed = f'{lm2.group(1)}ptr{lm2.group(3)}'
                reg_types[reg] = 'ptr'

        # load i64 → load %SeenString when used as %SeenString (e.g. in phi)
        lm_i2s = re.match(r'(\s*%\d+\s*=\s*load\s+)(i64)(,\s*ptr\s+\S+.*)', fixed)
        if lm_i2s:
            reg = re.match(r'\s*(%\d+)', fixed).group(1)
            if _is_used_as_type(reg, '%SeenString', func_lines):
                fixed = f'{lm_i2s.group(1)}%SeenString{lm_i2s.group(3)}'
                reg_types[reg] = '%SeenString'

        # load ptr → load i64 when used in icmp/arith with i64
        # But NOT if also used as %SeenString (struct types take precedence)
        lm_p2i = re.match(r'(\s*%\d+\s*=\s*load\s+)(ptr)(,\s*ptr\s+\S+.*)', fixed)
        if lm_p2i:
            reg = re.match(r'\s*(%\d+)', fixed).group(1)
            if _is_used_as_type(reg, 'i64', func_lines) and \
               not _is_used_as_type(reg, '%SeenString', func_lines):
                fixed = f'{lm_p2i.group(1)}i64{lm_p2i.group(3)}'
                reg_types[reg] = 'i64'

        # load i64 → load %SeenString when return type is %SeenString and
        # this reg is returned directly
        if func_ret_type == '%SeenString':
            lm3 = re.match(r'(\s*%\d+\s*=\s*load\s+)(i64)(,\s*ptr\s+\S+.*)', fixed)
            if lm3:
                reg = re.match(r'\s*(%\d+)', fixed).group(1)
                # Check if this reg is returned
                for fl in func_lines:
                    if re.search(rf'ret\s+\S+\s+{re.escape(reg)}\b', fl.strip()):
                        fixed = f'{lm3.group(1)}%SeenString{lm3.group(3)}'
                        reg_types[reg] = '%SeenString'
                        break

        pass1.append(fixed)

    # Pass 2: Fix stores, calls, rets, and icmp
    result = []
    for line in pass1:
        fixed = line

        # Fix store type mismatches
        sm = re.search(r'store\s+(ptr|i64|i1|%SeenString|%SeenArray)\s+(%\d+),\s*ptr', fixed)
        if sm:
            stated = sm.group(1)
            reg = sm.group(2)
            actual = reg_types.get(reg)
            if actual and actual != stated:
                fixed = fixed.replace(f'store {stated} {reg},', f'store {actual} {reg},', 1)

        # Fix icmp type mismatches: icmp ne i64 %N, 0 where %N is i1
        im = re.search(r'(icmp\s+\w+\s+)(i64)(\s+%\d+)', fixed)
        if im:
            reg_m = re.search(r'(icmp\s+\w+\s+i64\s+)(%\d+)', fixed)
            if reg_m:
                reg = reg_m.group(2)
                actual = reg_types.get(reg)
                if actual == 'i1':
                    # Replace: icmp ne i64 %N, 0 → icmp ne i1 %N, 0
                    fixed = re.sub(r'icmp\s+(\w+)\s+i64\s+' + re.escape(reg) + r',\s*0',
                                  f'icmp \\1 i1 {reg}, 0', fixed)

        # Fix phi type mismatches
        phi_m = re.match(r'(\s*(%\d+)\s*=\s*phi\s+)(\S+)(\s+.*)', fixed)
        if phi_m:
            phi_reg_name = phi_m.group(2)
            phi_type = phi_m.group(3)
            phi_rest = phi_m.group(4)
            phi_vals = re.findall(r'\[\s*(%\d+)\s*,', phi_rest)
            indent = re.match(r'(\s*)', fixed).group(1)

            # Count types among phi values
            type_counts = {}
            for pv in phi_vals:
                actual = reg_types.get(pv, phi_type)
                type_counts[actual] = type_counts.get(actual, 0) + 1

            if len(type_counts) == 1:
                # All values agree on a type different from phi_type
                agreed_type = list(type_counts.keys())[0]
                if agreed_type != phi_type:
                    new_rest = phi_rest
                    if phi_type == 'ptr' and agreed_type != 'ptr':
                        new_rest = new_rest.replace('null', '0')
                    elif phi_type != 'ptr' and agreed_type == 'ptr':
                        new_rest = re.sub(r'\[\s*0\s*,', '[ null,', new_rest)
                    fixed = f'{phi_m.group(1)}{agreed_type}{new_rest}'
                    reg_types[phi_reg_name] = agreed_type
            elif len(type_counts) > 1:
                # Mixed types — pick the most common type, insert casts for others
                # Use phi_type as the target if it's one of the types, otherwise pick majority
                target_type = phi_type if phi_type in type_counts else max(type_counts, key=type_counts.get)
                # For each mismatched value, insert a cast BEFORE the phi's predecessor branch
                # Since we can't easily insert before branches in predecessors,
                # we use extractvalue/bitcast approach: change the phi type to i64
                # (the universal Seen type) and cast SeenString values via extractvalue
                if target_type == 'i64' or (phi_type == 'i64'):
                    # Keep phi as i64, for %SeenString values extract the i64 field 0
                    for pv in phi_vals:
                        actual = reg_types.get(pv)
                        if actual == '%SeenString' and phi_type == 'i64':
                            # Insert extractvalue before this phi (in the phi's block)
                            next_num = _next_reg_num(reg_types)
                            ext_reg = f'%{next_num}'
                            result.append(f'{indent}{ext_reg} = extractvalue %SeenString {pv}, 0')
                            # Replace the value in the phi
                            fixed = fixed.replace(f'[ {pv},', f'[ {ext_reg},')
                            reg_types[ext_reg] = 'i64'

        # Fix br i1 %N where %N is not i1 — insert icmp ne TYPE %N, 0
        br_m = re.match(r'(\s*)(br\s+i1\s+)(%\d+)(,.*)', fixed)
        if br_m:
            reg = br_m.group(3)
            actual = reg_types.get(reg)
            if actual and actual != 'i1':
                # Insert comparison before branch
                next_num = _next_reg_num(reg_types)
                cmp_reg = f'%{next_num}'
                zero_val = 'null' if actual == 'ptr' else '0'
                result.append(f'{br_m.group(1)}{cmp_reg} = icmp ne {actual} {reg}, {zero_val}')
                fixed = f'{br_m.group(1)}br i1 {cmp_reg}{br_m.group(4)}'
                reg_types[cmp_reg] = 'i1'

        # Fix call argument types
        cm = re.search(r'(call\s+\S+\s+@\w+\()([^)]*)\)', fixed)
        if cm:
            args_str = cm.group(2)
            if args_str.strip():
                new_args = _fix_call_args(args_str, reg_types)
                if new_args != args_str:
                    fixed = fixed.replace(f'({args_str})', f'({new_args})', 1)

        # Fix ret type mismatches — ensure return value matches function type
        rm = re.match(r'(\s*)(ret\s+)(\S+)(\s+)(%\d+)(.*)', fixed)
        if rm and rm.group(3) != 'void' and func_ret_type and func_ret_type != 'void':
            stated = rm.group(3)
            reg = rm.group(5)
            actual = reg_types.get(reg, stated)
            indent = rm.group(1)

            if stated != func_ret_type or actual != func_ret_type:
                if actual == 'ptr' and func_ret_type == '%SeenString':
                    # Insert load %SeenString from ptr before ret
                    next_reg_num = _next_reg_num(reg_types)
                    load_reg = f'%{next_reg_num}'
                    result.append(f'{indent}{load_reg} = load %SeenString, ptr {reg}')
                    fixed = f'{indent}ret %SeenString {load_reg}'
                    reg_types[load_reg] = '%SeenString'
                elif actual == 'ptr' and func_ret_type == 'i64':
                    # Insert ptrtoint
                    next_reg_num = _next_reg_num(reg_types)
                    cast_reg = f'%{next_reg_num}'
                    result.append(f'{indent}{cast_reg} = ptrtoint ptr {reg} to i64')
                    fixed = f'{indent}ret i64 {cast_reg}'
                    reg_types[cast_reg] = 'i64'
                elif actual == func_ret_type:
                    # Just fix the ret type annotation
                    fixed = f'{indent}ret {func_ret_type} {reg}{rm.group(6)}'
                else:
                    # Just fix the ret type to match function
                    fixed = f'{indent}ret {func_ret_type} {reg}{rm.group(6)}'

        result.append(fixed)

    return result


def _next_reg_num(reg_types):
    """Get the next available register number."""
    max_num = 0
    for reg in reg_types:
        m = re.match(r'%(\d+)', reg)
        if m:
            max_num = max(max_num, int(m.group(1)))
    return max_num + 1


def _fix_call_args(args_str, reg_types):
    """Fix argument types in function calls."""
    args = _split_args(args_str)
    fixed = []
    for arg in args:
        a = arg.strip()
        m = re.match(r'(ptr|i64|i32|i1|float|double|%SeenString|%SeenArray)\s+(%\d+)$', a)
        if m:
            stated = m.group(1)
            reg = m.group(2)
            actual = reg_types.get(reg)
            if actual and actual != stated:
                a = f'{actual} {reg}'
        fixed.append(a)
    return ', '.join(fixed)


def _split_args(args_str):
    """Split call args respecting nesting."""
    args = []
    depth = 0
    cur = ''
    for c in args_str:
        if c in '({':
            depth += 1
            cur += c
        elif c in ')}':
            depth -= 1
            cur += c
        elif c == ',' and depth == 0:
            args.append(cur)
            cur = ''
        else:
            cur += c
    if cur.strip():
        args.append(cur)
    return args


def fix_empty_type(content):
    """Fix empty-type store/load instructions from frozen compiler.

    The frozen compiler's getFieldType returns "" for unknown LLVMIRGenerator
    fields (e.g. new fields added after the frozen binary was built). This
    produces `store  %val, ptr %ptr` and `%r = load , ptr %ptr` with missing
    types. All Seen class types are i64 handles, so defaulting to i64 is safe.
    """
    # Fix: store  %val, ptr → store i64 %val, ptr  (double space = empty type)
    content = re.sub(r'store  (%\d+), ptr', r'store i64 \1, ptr', content)
    # Fix: load , ptr → load i64, ptr  (empty type before comma)
    content = re.sub(r'= load , ptr', '= load i64, ptr', content)
    return content


def fix_all(content, all_module_files=None):
    """Apply all fixes in order."""
    content = fix_declare_define_conflicts(content)
    content = fix_invalid_function_names(content)
    content = fix_struct_zero(content)
    content = fix_ptr_null(content)
    content = fix_bare_string_refs(content, all_module_files)
    content = fix_undefined_symbols(content)
    content = fix_duplicate_globals(content)
    content = fix_type_mismatches(content)
    content = fix_empty_type(content)
    content = fix_ssa_numbering(content)
    return content


def main():
    if len(sys.argv) < 2:
        print("Usage: fix_ir.py <file.ll> [other_module_files...]", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    # Additional module files for cross-module string constant resolution
    all_module_files = sys.argv[2:] if len(sys.argv) > 2 else None

    # Auto-discover sibling module files if not provided
    if not all_module_files:
        import glob
        import os
        dirn = os.path.dirname(path)
        if not dirn:
            dirn = '/tmp'
        all_module_files = glob.glob(os.path.join(dirn, 'seen_module_*.ll'))

    with open(path) as f:
        original = f.read()

    fixed = fix_all(original, all_module_files)

    if fixed != original:
        with open(path, 'w') as f:
            f.write(fixed)
        print(f'  IR fixup applied to {path}', file=sys.stderr)


if __name__ == '__main__':
    main()
