[package]
name = "seen_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
seen_compiler = { path = "../seen_compiler" }
# For CLI argument parsing
clap = { version = "4.5.4", features = ["derive"] }
# For error handling
anyhow = "1.0.82"
# For logging
env_logger = "0.11.3"
log = "0.4.21"