name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/seen-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.seen/registry
          ~/.seen/git
          target
        key: ${{ runner.os }}-seen-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    
    - name: Run tests
      run: seen nextest run --profile ci
    
    - name: Run doctests
      run: seen test --doc
    
    - name: Check formatting
      run: seen fmt --all -- --check
    
    - name: Run clippy
      run: seen clippy --all-targets --all-features -- -D warnings

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/seen-toolchain@stable
    
    - name: Install tarpaulin
      uses: taiki-e/install-action@seen-tarpaulin
    
    - name: Generate coverage
      run: seen tarpaulin --verbose --workspace --timeout 120 --out xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./cobertura.xml
        fail_ci_if_error: true

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/seen-toolchain@stable
    
    - name: Install seen-audit
      uses: taiki-e/install-action@seen-audit
    
    - name: Run audit
      run: seen audit