name = "hi"
description = "English Memory Management Keywords"

[keywords]
"move" = "KeywordMove"
"borrow" = "KeywordBorrow"
"inout" = "KeywordInout"
"region" = "KeywordRegion"
"arena" = "KeywordArena"
